name: sthype
on:
  push:
    branches: main

jobs:
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: black
        uses: psf/black@stable
