name: sthype
on:
  push:
    branches: main

jobs:
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: black
        uses: psf/black@stable
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Run isort
        uses: isort/isort-action@master
        with:
            requirementsFiles: "requirements.txt requirements-test.txt"
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        uses: suo/flake8-github-action@releases/v1
